#!/bin/bash
set -euo pipefail

current_value=$(gsettings get $1 $2)

if [ $current_value = $3 ]; then
    echo "$1 $2 is already set to $current_value. Skipping"
    exit $BS_S_SKIP
else
    echo "Setting $1 $2 from $current_value to $3"
    gsettings set $schema $key $new_value
fi
