#!/bin/bash
set -euo pipefail

if (which gsettings > /dev/null); then
    # TODO: Move to ubuntu specific config?
    # Unset emoji hotkey C-., added in Ubuntu 21.10
    if (gsettings list-recursively | grep "<Control>period" > /dev/null); then
        gsettings set org.freedesktop.ibus.panel.emoji hotkey "[]"
    else
        exit $BS_S_SKIP
    fi
fi

# TODO rebind for Ubuntu: org.gnome.Terminal.Legacy.Keybindings
#local profile = $(gsettings get org.gnome.Terminal.ProfilesList default | tr -d \')

#gsettings set "org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/profiles:/:$profile/" default-size-columns 150

#dconf write /org/gnome/terminal/legacy/keybindings/copy "'<Super>c'" # default <Control><Shift>c
#dconf write /org/gnome/terminal/legacy/keybindings/paste "'<Super>v'" # default <Control><Shift>v
