#!/bin/bash
set -euo pipefail

which alacritty > /dev/null && echo "alacritty is already installed" && exit $BS_S_SKIP

case $(uname -s) in
    Linux*)
        if (which apt-get > /dev/null); then
            apt-get install cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev python3
        else
            echo "Unknown package manager."
            exit $BS_S_FAIL
        fi

        asdf install rust stable
        asdf global rust stable

        git clone https://github.com/alacritty/alacritty.git ~/workspace/oss/alacritty
        cd ~/workspace/oss/alacritty
        cargo build --release
        sudo mv target/release/alacritty /usr/bin/alacritty
        sudo mv extra/windows/alacritty.ico /usr/share/icons/alacritty.ico
        sudo chown root:root /usr/bin/alacritty
        sudo chown root:root /usr/share/icons/alacritty.ico
        sudo cat > /usr/share/applications/alacritty.desktop <<- EOF
             [Desktop Entry]
             Type=Application
             Name=Alacritty
             Exec=/usr/bin/alacritty
             Icon=/usr/share/icons/alacritty.ico
             Keywords=Terminal
             Categories=Utility;Terminal
EOF

        # TODO: Drop alacritty icon in bar
        ;;
    Darwin*)
        curl -Lo $HOME/Downloads/alacritty.dmg $(curl -s https://api.github.com/repos/alacritty/alacritty/releases/latest | grep -o 'https://.*.dmg')
        hdiutil attach $HOME/Downloads/alacritty.dmg
        sudo cp /Volumes/Alacritty/Alacritty.app /Applications/
        hdiutil unmount /Volumes/Alacritty
        rm $HOME/Downloads/alacritty.dmg

        # TODO: Drop alacritty icon in dock

        postinstall "Alacritty must be given Full Disk Access in System Preferences > Security & Privacy > Privacy"
        ;;
    *)
        echo "Unhandled OS $(uname -s) detected."
        exit $BS_S_FAIL
        ;;
esac
