#!/bin/bash
set -euo pipefail

which emacs > /dev/null && echo "emacs is already installed." && exit $BS_S_SKIP

case $(uname -s) in
    Linux*)
        if (which apt-get > /dev/null); then
            apt-get install emacs
            # TODO: Drop emacs shortcut in bar
        else
            echo "Unknown package manager."
            exit $BS_S_FAIL
        fi
        ;;
    Darwin*)
        local latest=$(curl https://emacsformacosx.com/download/emacs-builds/ | grep -E '"Emacs-[0-9\.\-]+-universal.dmg"' | sed -re 's/.*"(Emacs-[0-9\.\-]+-universal.dmg)".*([0-9]{4}-[0-9]{2}-[0-9]{2}).*/\2 \1/g' | sort -nr | head -1 | sed 's/^[0-9\-]* //g')

        curl -Lo $HOME/Downloads/emacs.dmg https://emacsformacosx.com/emacs-builds/$latest
        hdiutil attach $HOME/Downloads/emacs.dmg
        sudo cp /Volumes/Emacs/Emacs.app /Applications/
        hdiutil unmount /Volumes/Emacs
        rm $HOME/Downloads/emacs.dmg

        # Fix full disk access issues related to permissions being
        # granted to emacs but not the rubyscript which launches it.
        # https://github.com/caldwell/build-emacs/issues/84#issuecomment-545754668
        local prev_dir = pwd
        cd /Applications/Emacs.app/Contents/MacOS
        mv Emacs Emacs.old
        ln -s Emacs-x86_64-10_14 Emacs
        cd $prev_dir

        # TODO: Drop emacs shortcut in dock

        postinstall "Emacs must be given Full Disk Access in System Preferences > Security & Privacy > Privacy"
        ;;
    *)
        echo "Unhandled OS $(uname -s) detected."
        exit $BS_S_FAIL
        ;;
esac
