#!/bin/bash
set -euo pipefail

[ -d $HOME/.oh-my-zsh ] && echo "ohmyzsh is already installed." && exit $BS_S_SKIP

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
