#!/bin/bash
set -euo pipefail

font_dir=""

case $(uname -s) in
    Linux*)
        font_dir=$HOME/.local/share/fonts
        ;;
    Darwin*)
        font_dir=$HOME/Library/Fonts
        ;;
    *)
        echo "Unhandled OS $(uname -s) detected."
        exit $BS_S_FAIL
        ;;
esac

mkdir -p $font_dir
installed=0

for font_name in \
    "MesloLGS NF Regular.ttf" \
    "MesloLGS NF Bold.ttf" \
    "MesloLGS NF Italic.ttf" \
    "MesloLGS NF Bold Italic.ttf"
do
    if ! [ -f "$font_dir/$font_name" ]; then
        curl -o "$font_dir/$font_name" "https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/$(echo $font_name | sed 's/ /%20g')"
        installed=1
    else
        echo "'$font_name' is already installed; skipping"
    fi
done

if [ $installed -eq 1 ]; then
    which fc-cache && fc-cache -f -v
else
    echo "No fonts installed."
    exit $BS_S_SKIP
fi
