#!/bin/bash
set -euo pipefail

changed=0

if [ -f "$HOME/.emacs.d/core/prelude-core.el" ]; then
    echo "prelude is already installed."
else
    echo "installing prelude"
    curl -L https://github.com/bbatsov/prelude/raw/master/utils/installer.sh | sh
    changed=1
fi

if [ ! -L $HOME/.emacs.d/personal ]; then
    echo "Symlinking .emacs.d/personal to .config/prelude/personal"
    rm -r $HOME/.emacs.d/personal
    ln -s $HOME/.config/prelude/personal $HOME/.emacs.d/personal
    changed=1
fi

if [ $changed -eq 0 ]; then
    echo "No changes made"
    exit $BS_S_SKIP
fi
