#!/bin/bash
set -euo pipefail

changed=0

if [ -d "$HOME/.tmux/plugins/tpm" ]; then
    echo "Tmux Plugin Manager is already installed"
else
    echo "Installing Tmux Plugin Manager"
    git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
    changed=1
fi

case $(uname -s) in
    Linux*)
        # Ensure python3-pip is available
        if (which apt-get > /dev/null); then
            if (dpkg -s python3-pip > /dev/null); then
                echo "python3-pip already installed"
            else
                sudo apt-get install python3-pip
                changed=1
            fi
        else
            echo "Unhandled package manager"
            exit $BS_S_FAIL
        fi
        ;;
    *)
        echo "Unhandled OS $(uname -s)"
        exit $BS_S_FAIL
        ;;
esac

# Install tmux-window-name requirements
# See: https://github.com/ofirgall/tmux-window-name#installation
if (pip show libtmux > /dev/null && pip show dataclasses > /dev/null); then
    echo "libtmux and dataclasses are already installed"
else
    echo "Installing libtmux and dataclasses"
    python3 -m pip install libtmux dataclasses --user
    changed=1
fi

# Install tmux-yank requirements
# See: https://github.com/tmux-plugins/tmux-yank#requirements
case $(uname -s) in
    Linux*)
        if (which xsel > /dev/null); then
            echo "xsel is already installed"
        elif (which apt-get > /dev/null); then
            echo "Installing xsel"
            sudo apt-get install xsel
            changed=1
        else
            "Unknown package manager."
            exit $BS_S_FAIL
        fi
        ;;
    Darwin*)
        if (which reattach-to-user-namespace > /dev/null); then
            echo "reattach-to-user-namespace is already installed"
        elif (which brew > /dev/null); then
            echo "Installing reattach-to-user-namespace"
            brew install reattach-to-user-namespace
            changed=1
        else
            echo "Homebrew is not installed"
            exit $BS_S_FAIL
        fi
        ;;
    *)
        echo "Unknown operating system"
        exit $BS_S_FAIL
esac

if [ $changed -eq 1 ]; then
    echo "Installing plugins"
    # TODO: verify that .tmux.conf gets copied before bootstrap
    $HOME/.tmux/plugins/tpm/bin/install_plugins
else
    echo "No changes made."
    exit $BS_S_SKIP
fi
