# Theme: tokyo-night: https://github.com/zatchheems/tokyo-night-alacritty-theme/blob/main/tokyo-night.yaml
[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.cursor]
cursor = "#a9b1d6"
text = "#32344a"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[colors.selection]
background = "#373b41"
text = "#a9b1d6"

[debug]
log_level = "Warn"

[font]
size = 11.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "FantasqueSansM Nerd Font"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u001BB"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BF"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[scrolling]
history = 100000
multiplier = 3

[window]
decorations = "full"
dynamic_padding = false
option_as_alt= "Both"
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
